apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath
    volume.kubernetes.io/selected-node: hp03
    volume.kubernetes.io/storage-provisioner: microk8s.io/hostpath
  finalizers:
  - kubernetes.io/pvc-protection
  name: ollama-qwer-pvc
  namespace: ollama-qwer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
