apiVersion: v1
kind: Service
metadata:
  name: ollama-webui-service
  namespace: ollama-qwer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ollama-qwer-webui