apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: deepseek
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hemas9
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hemas9/volumes/ollama"