apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/backend/data"
          name: open-webui-storage
        env:
        - name: OLLAMA_HOST
          value: "ollama-service"
        - name: OLLAMA_PORT
          value: "11434"
      volumes:
      - name: open-webui-storage
        persistentVolumeClaim:
          claimName: open-webui-pvc