apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
  namespace: deepseek
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/backend/data"